languageCode:           "en"
title:                  "Bootstrap"
baseURL:                "https://getbootstrap.com"
enableInlineShortcodes: true

markup:
  goldmark:
    renderer:
      unsafe:           true
  highlight:
    noClasses:          false

buildDrafts:            true
buildFuture:            true

enableRobotsTXT:        true
metaDataFormat:         "yaml"
disableKinds:           ["404", "taxonomy", "taxonomyTerm", "RSS"]

blackfriday:
  fractions:            false

publishDir:             "_gh_pages"

module:
  mounts:
    - source:           dist
      target:           static/docs/5.0/dist
    - source:           site/assets
      target:           assets
    - source:           site/content
      target:           content
    - source:           site/data
      target:           data
    - source:           site/layouts
      target:           layouts
    - source:           site/static
      target:           static
    - source:           site/static/docs/5.0/assets/img/favicons/apple-touch-icon.png
      target:           static/apple-touch-icon.png
    - source:           site/static/docs/5.0/assets/img/favicons/favicon.ico
      target:           static/favicon.ico

params:
  description:          "The most popular HTML, CSS, and JS library in the world."
  authors:              "Mark Otto, Jacob Thornton, and Bootstrap contributors"
  social_image_path:    /docs/5.0/assets/brand/bootstrap-social.png
  social_logo_path:     /docs/5.0/assets/brand/bootstrap-social-logo.png

  current_version:      "5.0.0-alpha1"
  current_ruby_version: "5.0.0-alpha1"
  docs_version:         "5.0"
  rfs_version:          "9.0.2"
  repo:                 "https://github.com/twbs/bootstrap"
  twitter:              "getbootstrap"
  slack:                "https://bootstrap-slack.herokuapp.com/"
  opencollective:       "https://opencollective.com/bootstrap"
  blog:                 "https://blog.getbootstrap.com/"
  expo:                 "https://expo.getbootstrap.com/"
  themes:               "https://themes.getbootstrap.com/"
  icons:                "https://icons.getbootstrap.com/"

  download:
    source:             "https://github.com/twbs/bootstrap/archive/v5.0.0-alpha1.zip"
    dist:               "https://github.com/twbs/bootstrap/releases/download/v5.0.0-alpha1/bootstrap-5.0.0-alpha1-dist.zip"

  cdn:
    # See https://www.srihash.org for info on how to generate the hashes
    css:              "https://stackpath.bootstrapcdn.com/bootstrap/5.0.0-alpha1/css/bootstrap.min.css"
    css_hash:         "sha384-2XyWmvELyo8yyJahbN90VbgDdopCK+U0dTqK6jKsZ2GApTRUK8C8vZok3tyHbi+a"
    js:               "https://stackpath.bootstrapcdn.com/bootstrap/5.0.0-alpha1/js/bootstrap.min.js"
    js_hash:          "sha384-t/tlgNKoDQMqe5TV7+apRV8M6e9v1y3mVJqgkEIcv43HsrGmZ0lLVEIqIwoyjRrT"
    js_bundle:        "https://stackpath.bootstrapcdn.com/bootstrap/5.0.0-alpha1/js/bootstrap.bundle.min.js"
    js_bundle_hash:   "sha384-/oVJOF4IgwhNqrSPiXrP+h1t1OHNG/w3B13VMCK4uWs0MxAIv+1EQpCgRxBO5bDv"
    popper:           "https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
    popper_hash:      "sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
